import ClientOnly from './components/ClientOnly'
import Navbar from './components/Navbar/Navbar'
import './globals.css'
import { Providers } from './store/provider';

export const metadata = {
  title: 'Evaluacion Tecnica',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ClientOnly>
          <Navbar />
          <Providers>
            {children}
          </Providers>
        </ClientOnly>
      </body>
    </html>
  )
}
